language: python
python:
- '3.7'
- '3.8'
- '3.9'
before_install:
# Travis pre-installs an old version of numpy.
# It conflicts with the latest one, see https://github.com/numpy/numpy/issues/12736
- pip uninstall -y numpy # will uninstall your numpy from cache
- pip uninstall -y numpy # will uninstall preinstalled numpy 1.15.2
- pip uninstall -y numpy # just in case
#after_success:
#- codecov --file coverage/lcov.info --disable search
install:
- pip install --upgrade pip
- python setup.py install
script:
- pytest -v
env:
  global:
    secure: YRtXR3o1SzyFItYld8//uO8lvTFpFfgc7oj6HcpLTAPlpgthbq9GBHa1HqgY9ZSYPMuNjyncYtlm49Hv432TxY2+a0G/w2scA5IzvpcT1SCq/iRla5bLI7XlU0fGYR3efkDtvyMYwH43IpBpVUTUMT72GXWA98h7EbAVARdrl2JN8f91V+SkYCeObz+WE/dBpkaI3a6aFSBbUrxouj61FAbKeHcn7mSvTArsWoAdZxxUNxfW+LbtTf8EG/swOFvJwncti5EmCFTJHjZB/xc5LjRVDo5544YyxXxofRxhmTPsmMWmiFzb1hPAECJCKjkmmEvuEDJ1PcoLmkIYvbzpXYoe7ab+/Ai3Tqr90eY2Ab69OxlzDWyTFmD0QW1lzH+fPBygaox2PdOr22WualINpxDJ8bu6awY0w9ONhp8GJW1uNWzCVu8SgzrkkxvUlSTAYh/KZFdMBwbnMVbatqIVhfcKaFrlpe7e1HP6WCMvrs7n+31/VnVqCvXsUxos+FmZ+3deuZFOpgeOF9SyJhCwgboyRVTqeE+G0RyiFGKPuXNAcdMsOIyGmyvlULXcl7DL+pzIWnTFkTVnR8Jbau1V6SgsXsdj3IcF0YUrjyplYagZTQECMat2MRkbjbzww4szrxUrpGChFoUkqM0f606I6wMsCg6HC7y8S9ucW0InAEk=
